[tool.poetry]
name = "blog"
version = "0.1.0"
authors = [
    "QuantumGhost <obelisk.reg+github@gmail.com>"
]
description = "Blog of QuantumGhost"

[tool.poetry.dependencies]
python = "^3.7"
pelican = "^4.0"
invoke = "^1.2"
typogrify = "^2.0"
ghp-import = "0.5.5"

[tool.poetry.dev-dependencies]
black = "19.3b0"

[tool.black]
line-length = 88
target-version = ['py37']
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | plugins          # ignore vendored plugins
  | themes           # ingore codes in themes
)
'''
